# Generated by Django 5.1.1 on 2024-10-02 18:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="token",
            new_name="tc",
        ),
    ]
